version: '3.1'

services:

  mongodb:
    image: mongo 
    restart: always
    container_name: my-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - ./data:/data/db
      - ./data/log:/var/log/mongodb/
    ports:
      - 27017:27017

networks:
    default:
          name: docker_airflow_default
          external: true